name = "Relucent"
uuid = "d4a0f349-cd98-4799-b7a0-96cbe38b225a"
authors = ["Blake B. Gaines"]
version = "0.9.0"

[compat]
julia = "1.10.10"
PythonCall = "0.9"

[extras]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PythonCall", "Test"]

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
